name: Generate HTML Pages for GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  generate_html:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get install jq

      - name: Read JSON and generate HTML files
        run: |
          # Define JSON file
          JSON_FILE="articles.json"
          
          # Create docroot directory
          mkdir -p docroot

          # Read each object in the JSON array
          cat $JSON_FILE | jq -c '.[]' | while read item; do
            # Extract path and html values from each object
            PATH=$(echo $item | jq -r '.path')
            HTML=$(echo $item | jq -r '.html')

            # Create directory if it doesn't exist
            DIR_NAME="docroot$(dirname $PATH)"
            mkdir -p $DIR_NAME

            # Write HTML content to the file
            echo "$HTML" > "$DIR_NAME/index.html"
          done

      - name: Commit and push generated files
        uses: EndBug/add-and-commit@v9
        with:
          message: "Generate HTML files for GitHub Pages"
          add: "docroot/*"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./docroot
          github_token: ${{ secrets.GITHUB_TOKEN }}
