name: Create HTML Files

on:
  push:
    branches:
      - main

jobs:
  create-files:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Read and process JSON file
      - name: Create files from JSON
        run: |
          # Read the JSON file
          json_data=$(cat articles.json)

          # Parse JSON and loop through objects
          echo "$json_data" | jq -c '.[]' | while read -r obj; do
            path=$(echo "$obj" | jq -r '.path')
            html=$(echo "$obj" | jq -r '.html')

            # Ensure the directory exists
            mkdir -p "$(dirname "$path")"

            # Write the HTML content to the file
            echo "$html" > "$path"
          done

      # Commit and push the changes back to the repository
      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Add HTML files from JSON"
          git push
