name: Deploy HTML Files to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Create files from JSON
      - name: Create HTML files from JSON
        run: |
          # Read the JSON file
          json_data=$(cat articles.json)

          # Parse JSON and loop through objects
          echo "$json_data" | jq -c '.[]' | while read -r obj; do
            path=$(echo "$obj" | jq -r '.path')
            html=$(echo "$obj" | jq -r '.html')

            # Ensure the directory exists under 'public' for GitHub Pages
            mkdir -p "public/$(dirname "$path")"

            # Write the HTML content to the file
            echo "$html" > "public/$path"
          done

      # Step 3: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public
